DROP TABLE IF EXISTS weapon;
DROP TABLE IF EXISTS defense;

CREATE TABLE weapon (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    attacks TEXT NOT NULL,
    skill INTEGER NOT NULL,
    strength INTEGER NOT NULL,
    ap INTEGER NOT NULL,
    damage TEXT NOT NULL
);

CREATE TABLE defense (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    toughness INTEGER NOT NULL,
    save INTEGER NOT NULL
);